# Generated by Django 3.1.2 on 2020-11-01 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_comment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_file_paths',
            field=models.TextField(blank=True, null=True),
        ),
    ]
